#ifndef ADD
#define ADD(x, y) // nothing, to make the in-IDE compiler happy
#endif

ADD(0x0001, IMAGE_LIBRARY_PROCESS_INIT)
ADD(0x0002, IMAGE_LIBRARY_PROCESS_TERM)
ADD(0x0004, IMAGE_LIBRARY_THREAD_INIT)
ADD(0x0008, IMAGE_LIBRARY_THREAD_TERM)
ADD(0x0020, IMAGE_DLLCHARACTERISTICS_HIGH_ENTROPY_VA)
ADD(0x0040, IMAGE_DLLCHARACTERISTICS_DYNAMIC_BASE)
ADD(0x0080, IMAGE_DLLCHARACTERISTICS_FORCE_INTEGRITY)
ADD(0x0100, IMAGE_DLLCHARACTERISTICS_NX_COMPAT)
ADD(0x0200, IMAGE_DLLCHARACTERISTICS_NO_ISOLATION)
ADD(0x0400, IMAGE_DLLCHARACTERISTICS_NO_SEH)
ADD(0x0800, IMAGE_DLLCHARACTERISTICS_NO_BIND)
ADD(0x1000, IMAGE_DLLCHARACTERISTICS_APPCONTAINER)
ADD(0x2000, IMAGE_DLLCHARACTERISTICS_WDM_DRIVER)
ADD(0x4000, IMAGE_DLLCHARACTERISTICS_GUARD_CF)
ADD(0x8000, IMAGE_DLLCHARACTERISTICS_TERMINAL_SERVER_AWARE)
