#ifndef ADD
#define ADD(x, y) // nothing, to make the in-IDE compiler happy
#endif

ADD(0, IMAGE_SUBSYSTEM_UNKNOWN)
ADD(1, IMAGE_SUBSYSTEM_NATIVE)
ADD(2, IMAGE_SUBSYSTEM_WINDOWS_GUI)
ADD(3, IMAGE_SUBSYSTEM_WINDOWS_CUI)
ADD(5, IMAGE_SUBSYSTEM_OS2_CUI)
ADD(7, IMAGE_SUBSYSTEM_POSIX_CUI)
ADD(8, IMAGE_SUBSYSTEM_NATIVE_WINDOWS)
ADD(9, IMAGE_SUBSYSTEM_WINDOWS_CE_GUI)
ADD(10, IMAGE_SUBSYSTEM_EFI_APPLICATION)
ADD(11, IMAGE_SUBSYSTEM_EFI_BOOT_SERVICE_DRIVER)
ADD(12, IMAGE_SUBSYSTEM_EFI_RUNTIME_DRIVER)
ADD(13, IMAGE_SUBSYSTEM_EFI_ROM)
ADD(14, IMAGE_SUBSYSTEM_XBOX)
ADD(16, IMAGE_SUBSYSTEM_WINDOWS_BOOT_APPLICATION)
